name: covid-xprize
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pandas=1.1.2
  - numpy=1.18.5
  - scikit-learn=0.23.2
  - scipy=1.5.2

  - plotly=4.11.0
  - matplotlib=3.3.2
  - pytest=6.1.1
  - nose=1.3.7
  - pip
  - jupyterlab
  - pip:
    - neat-python==0.92
    - tensorflow==2.2.1
    - keras==2.4.3

